package eu.linksmart.example.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-05-09T11:47:50.743+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "Calculator", 
                  wsdlLocation = "file:/C:/Users/Rasheed/dev/eclipse/linksmart.2.2/linksmart-service-example/calculator-ws-client/src/main/resources/calculator.wsdl",
                  targetNamespace = "http://calculator.example.linksmart.eu/") 
public class Calculator extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://calculator.example.linksmart.eu/", "Calculator");
    public final static QName CalculatorPort = new QName("http://calculator.example.linksmart.eu/", "CalculatorPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Rasheed/dev/eclipse/linksmart.2.2/linksmart-service-example/calculator-ws-client/src/main/resources/calculator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Calculator.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Rasheed/dev/eclipse/linksmart.2.2/linksmart-service-example/calculator-ws-client/src/main/resources/calculator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Calculator(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Calculator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Calculator() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Calculator(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Calculator(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Calculator(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CalculatorPortType
     */
    @WebEndpoint(name = "CalculatorPort")
    public CalculatorPortType getCalculatorPort() {
        return super.getPort(CalculatorPort, CalculatorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorPortType
     */
    @WebEndpoint(name = "CalculatorPort")
    public CalculatorPortType getCalculatorPort(WebServiceFeature... features) {
        return super.getPort(CalculatorPort, CalculatorPortType.class, features);
    }

}
