/*
 * In case of German law being applicable to this license agreement, the following warranty and liability terms shall apply:
 *
 * 1. Licensor shall be liable for any damages caused by wilful intent or malicious concealment of defects.
 * 2. Licensor's liability for gross negligence is limited to foreseeable, contractually typical damages.
 * 3. Licensor shall not be liable for damages caused by slight negligence, except in cases 
 *    of violation of essential contractual obligations (cardinal obligations). Licensee's claims for 
 *    such damages shall be statute barred within 12 months subsequent to the delivery of the software.
 * 4. As the Software is licensed on a royalty free basis, any liability of the Licensor for indirect damages 
 *    and consequential damages - except in cases of intent - is excluded.
 *
 * This limitation of liability shall also apply if this license agreement shall be subject to law 
 * stipulating liability clauses corresponding to German law.
 */
/**
 * Copyright (C) 2006-2010 [University of Paderborn]
 *                         the HYDRA consortium, EU project IST-2005-034891
 *
 * This file is part of LinkSmart.
 *
 * LinkSmart is free software: you can redistribute it and/or modify
 * it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
 * version 3 as published by the Free Software Foundation.
 *
 * LinkSmart is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with LinkSmart.  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.linksmart.limbo.storagemanagerdevice;


import java.util.Hashtable;
 import java.util.Dictionary;

import eu.linksmart.limbo.storagemanagerdevice.upnp.*;

/**
 * StorageManagerOpsImpl is generated by Limbo
 *
 * 
 */
public class StorageManagerOpsImpl {


	private StorageManagerDeviceDevice device;
	private StorageManagerUPnPService upnpService;
	createStorageDeviceAction createstoragedevice;
	createStorageDeviceLocalAction createstoragedevicelocal;
	deleteStorageDeviceAction deletestoragedevice;
	deleteStorageDeviceLocalAction deletestoragedevicelocal;
	getSupportedStorageDevicesAction getsupportedstoragedevices;
	getStorageDevicesAction getstoragedevices;
	getStorageDeviceConfigAction getstoragedeviceconfig;
	updateStorageDeviceAction updatestoragedevice;
	updateStorageDeviceLocalAction updatestoragedevicelocal;
	public StorageManagerOpsImpl(){
		this.device = StorageManagerDeviceActivator.getDevice();
		this.upnpService = (StorageManagerUPnPService)this.device.getService("urn:upnp-org:serviceId:StorageManager");		
		this.createstoragedevice = (createStorageDeviceAction)this.upnpService.getAction("createStorageDevice");
		this.createstoragedevicelocal = (createStorageDeviceLocalAction)this.upnpService.getAction("createStorageDeviceLocal");
		this.deletestoragedevice = (deleteStorageDeviceAction)this.upnpService.getAction("deleteStorageDevice");
		this.deletestoragedevicelocal = (deleteStorageDeviceLocalAction)this.upnpService.getAction("deleteStorageDeviceLocal");
		this.getsupportedstoragedevices = (getSupportedStorageDevicesAction)this.upnpService.getAction("getSupportedStorageDevices");
		this.getstoragedevices = (getStorageDevicesAction)this.upnpService.getAction("getStorageDevices");
		this.getstoragedeviceconfig = (getStorageDeviceConfigAction)this.upnpService.getAction("getStorageDeviceConfig");
		this.updatestoragedevice = (updateStorageDeviceAction)this.upnpService.getAction("updateStorageDevice");
		this.updatestoragedevicelocal = (updateStorageDeviceLocalAction)this.upnpService.getAction("updateStorageDeviceLocal");

	}

	public java.lang.String createStorageDevice(java.lang.String config ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("config",config);
		try{
			result = this.createstoragedevice.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String createStorageDeviceLocal(java.lang.String config ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("config",config);
		try{
			result = this.createstoragedevicelocal.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String deleteStorageDevice(java.lang.String id ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("id",id);
		try{
			result = this.deletestoragedevice.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String deleteStorageDeviceLocal(java.lang.String id ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("id",id);
		try{
			result = this.deletestoragedevicelocal.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String getSupportedStorageDevices(){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		try{
			result = this.getsupportedstoragedevices.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String getStorageDevices(){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		try{
			result = this.getstoragedevices.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String getStorageDeviceConfig(java.lang.String id ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("id",id);
		try{
			result = this.getstoragedeviceconfig.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String updateStorageDevice(java.lang.String config ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("config",config);
		try{
			result = this.updatestoragedevice.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}

	public java.lang.String updateStorageDeviceLocal(java.lang.String config ){
		Hashtable args = new Hashtable();
		Dictionary result = null;
		args.put("config",config);
		try{
			result = this.updatestoragedevicelocal.invoke(args);
		}catch(Exception e){
			e.printStackTrace();
		}return result.get("result").toString();
	}



}