;; Problem instance file auto-generated by PlanProblemGenerator. 
(define (problem protocolproblem)
	(:domain protocoldomain)
	(:objects 
did Stcp Sudp tcpinterface udpinterface udp tcp httpclientprotocol24)

	(:init
		;;types
		(Device did)
		(Service Stcp)
		(Service Sudp)
		;;relations
		(Has did Sudp)
		(Has did Stcp)
		(initiated did)
		(Channel did did)
		(Property httpclientprotocol24)
		(HasProperty did httpclientprotocol24)
		(PropertyValue did httpclientprotocol24 tcp)
		(Protocol tcp) (Protocol udp)
		(Realizes tcpinterface tcp) (Realizes udpinterface udp)
		(Provides Stcp tcp)
		(Provides Sudp udp)
		(Interface tcpinterface) (Interface udpinterface)
	)
	;; goal state specification
	(:goal 
		(and 
			(Has did Sudp)
			(Has did Stcp)
			(PropertyValue did httpclientprotocol24 udp)
		)
	)
)