;; Problem instance file auto-generated by PlanProblemGenerator. 
(define (problem protocolproblem)
	(:domain protocoldomain)
	(:objects 
deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb servicenamesc_udp_protocol servicenamesc_tcp_protocol tcpinterface udpinterface udp tcp httpclientprotocol24)

	(:init
		;;types
		(Device deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb)
		(Service servicenamesc_udp_protocol)
		(Service servicenamesc_tcp_protocol)
		;;relations
		(Has deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb servicenamesc_udp_protocol)
		(Has deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb servicenamesc_tcp_protocol)
		(initiated deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb)
		(started servicenamesc_udp_protocol)
		(started servicenamesc_tcp_protocol)
		(Channel deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb)
		(Property httpclientprotocol24)
		(HasProperty deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb httpclientprotocol24)
		(PropertyValue deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb httpclientprotocol24 tcp)
		(Protocol tcp) (Protocol udp)
		(Realizes tcpinterface tcp) (Realizes udpinterface udp)
		(Provides servicenamesc_tcp_protocol tcpinterface)
		(Provides servicenamesc_udp_protocol udpinterface)
		(Interface tcpinterface) (Interface udpinterface)
		(AvailableAt deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb tcpinterface)
		(AvailableAt deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb udpinterface)
	)
	;; goal state specification
	(:goal 
		(and 
			(Has deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb servicenamesc_udp_protocol)
			(Has deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb servicenamesc_tcp_protocol)
			(PropertyValue deviced77e6b53-f96a-4ce4-afa3-37d1dd9a00cb httpclientprotocol24 udp)
		)
	)
)