<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.upnp.linksmart.tid.es" xmlns:linksmart="http://linksmart.eu/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.upnp.linksmart.tid.es" xmlns:intf="http://ws.upnp.linksmart.tid.es" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->


   <wsdl:message name="GetDoorStatusRequest">

   </wsdl:message>

   <wsdl:message name="GetDoorStatusResponse">
   
       <wsdl:part name="doorStatus" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="DoorTrap">

      <wsdl:operation name="GetDoorStatus">

         <wsdl:input message="impl:GetDoorStatusRequest" name="GetDoorStatusRequest"/>

         <wsdl:output message="impl:GetDoorStatusResponse" name="GetDoorStatusResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DoorTrapSoapBinding" type="impl:DoorTrap">
	
	<linksmart:binding device="file:./resources/Device.owl#DoorTrap1"/>

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="GetDoorStatus">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="GetDoorStatusRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.upnp.linksmart.tid.es" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="GetDoorStatusResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.upnp.linksmart.tid.es" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DoorTrapService">

      <wsdl:port binding="impl:DoorTrapSoapBinding" name="DoorTrap">

         <wsdlsoap:address location="http://localhost:8082/axis/services/DoorTrap"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
