<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="http://eventmanager.linksmart.eu" name="EventSubscriberService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:impl="http://eventmanager.linksmart.eu" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://eventmanager.linksmart.eu" schemaLocation="EventSubscriberService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="notify">
    <part name="topic" type="xsd:string"/>
    <part name="event" type="impl:event"/>
  </message>
  <message name="notifyResponse">
    <part name="result" type="xsd:boolean"/>
  </message>
  <portType name="EventSubscriber">
    <operation name="notify" parameterOrder="topic event">
      <input message="impl:notify" name="notify"/>
      <output message="impl:notifyResponse" name="notifyResponse"/>
    </operation>
  </portType>
  <binding name="EventSubscriberPortBinding" type="impl:EventSubscriber">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="notify">
      <soap:operation soapAction="notify"/>
      <input name="notify">
        <soap:body use="literal" namespace="http://eventmanager.linksmart.eu"/>
      </input>
      <output name="notifyResponse">
        <soap:body use="literal" namespace="http://eventmanager.linksmart.eu"/>
      </output>
    </operation>
  </binding>
  <service name="EventSubscriberService">
    <port name="EventSubscriberPort" binding="impl:EventSubscriberPortBinding">
      <soap:address location="http://localhost"/>
    </port>
  </service>
</definitions>

