<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Klaus Marius Hansen (Ã
rhus Universitet) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:impl="http://flowmeter.device.eudomain.au.dk" targetNamespace="http://flowmeter.device.eudomain.au.dk" xmlns:linksmart="http://linksmart.eu/">
	<message name="getFlowValueRequest">
		<part name="deviceID" type="xs:string"/>
	</message>
	<message name="getFlowValueResponse">
		<part name="flow" type="xs:double"/>
	</message>
	<portType name="FlowMeterPort">
		<operation name="getFlowValue">
			<input message="impl:getFlowValueRequest" name="getFlowValueRequest"/>
			<output message="impl:getFlowValueResponse" name="getFlowValueResponse"/>
		</operation>
	</portType>
	<binding name="FlowMeterBinding" type="impl:FlowMeterPort">
		<linksmart:binding device="file:./resources/Device.owl#Flowmeter1"/>
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getFlowValue">
			<soap:operation soapAction="http://flowmeter.device.eudomain.au.dk/getFlowValue" style="rpc"/>
			<input name="getFlowValueRequest">
				<soap:body use="literal" namespace="http://flowmeter.device.eudomain.au.dk"/>
			</input>
			<output name="getFlowValueResponse">
				<soap:body use="literal" namespace="http://flowmeter.device.eudomain.au.dk"/>
			</output>
		</operation>
	</binding>
	<service name="FlowMeterService">
		<port name="FlowMeterPort" binding="impl:FlowMeterBinding">
			<soap:address location="http://localhost:8082/axis/services/FlowMeterService"/>
		</port>
	</service>
</definitions>
