<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.upnp.linksmart.tid.es" xmlns:linksmart="http://linksmart.eu/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.upnp.linksmart.tid.es" xmlns:intf="http://ws.upnp.linksmart.tid.es" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->


   <wsdl:message name="GetLastMotionDetectedRequest">

   </wsdl:message>

   <wsdl:message name="GetLastMotionDetectedResponse">
   
       <wsdl:part name="time" type="xsd:double"/>

   </wsdl:message>

   <wsdl:portType name="MotionDetector">

      <wsdl:operation name="GetLastMotionDetected">

         <wsdl:input message="impl:GetLastMotionDetectedRequest" name="GetLastMotionDetectedRequest"/>

         <wsdl:output message="impl:GetLastMotionDetectedResponse" name="GetLastMotionDetectedResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="MotionDetectorSoapBinding" type="impl:MotionDetector">
	
	<linksmart:binding device="file:./resources/Device.owl#MotionDetector1"/>

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="GetLastMotionDetected">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="GetLastMotionDetectedRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.upnp.linksmart.tid.es" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="GetLastMotionDetectedResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.upnp.linksmart.tid.es" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="MotionDetectorService">

      <wsdl:port binding="impl:MotionDetectorSoapBinding" name="MotionDetector">

         <wsdlsoap:address location="http://localhost:8082/axis/services/MotionDetector"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
