/*
 * In case of German law being applicable to this license agreement, the following warranty and liability terms shall apply:
 *
 * 1. Licensor shall be liable for any damages caused by wilful intent or malicious concealment of defects.
 * 2. Licensor's liability for gross negligence is limited to foreseeable, contractually typical damages.
 * 3. Licensor shall not be liable for damages caused by slight negligence, except in cases 
 *    of violation of essential contractual obligations (cardinal obligations). Licensee's claims for 
 *    such damages shall be statute barred within 12 months subsequent to the delivery of the software.
 * 4. As the Software is licensed on a royalty free basis, any liability of the Licensor for indirect damages 
 *    and consequential damages - except in cases of intent - is excluded.
 *
 * This limitation of liability shall also apply if this license agreement shall be subject to law 
 * stipulating liability clauses corresponding to German law.
 */
package eu.linksmart.tools;

import org.apache.log4j.HTMLLayout;

import java.text.SimpleDateFormat;
import java.util.*;

/**
 * A custom HTMLLayout for logfiles generated by Log4J
 * It has not many differences compared to the original HTMLLayout, but it allows some tricks needed by the frontend
 * 
 * @author schuette
 *
 */
public class HTMLLogger extends HTMLLayout {

	public HTMLLogger() {
		super();
	}
	
	/**
	 * Overrides HTMLLayout.getHeader() to define a custom header, using our own css-file
	 */
	public String getHeader() {
		String header = "";

		header += "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">";
		
		header += "<html xmlns=\"http://www.w3.org/1999/xhtml\">";
		header += "<head>";
		header += "  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\" />";
		header += "</head>";
		
		header += "<body class=\"logfile_body\">";
		header += "<br />";
		header += "<table cellspacing=\"0\" cellpadding=\"4\" border=\"1\" width=\"100%\" class=\"logfile\">";
		header += "<tr>";
		header += "<th class=\"logfile\">Time</th>";
		//header += "<th class=\"logfile\">Thread</th>";
		header += "<th class=\"logfile\">Level</th>";
		header += "<th class=\"logfile\">Category</th>";
		header += "<th class=\"logfile\">Message</th>";
		header += "</tr>";
		
		return header;
	}
	
	/**
	 * Overrides HTMLLayout.format(LoggingEvent) to define a row in custom layout
	 */
//	public String format(LoggingEvent event) {
//		String logEntry = "";
//		String levelColor="#000000";
//		SimpleDateFormat df = new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss.S" );
//		
//		if (event.getLevel().toString().equals("DEBUG"))
//			levelColor = "#aaaaaa"; 
//		if (event.getLevel().toString().equals("INFO"))
//			levelColor = "#00aa00"; 
//		if (event.getLevel().toString().equals("WARN"))
//			levelColor = "#aaaa00"; 
//		if (event.getLevel().toString().equals("ERROR"))
//			levelColor = "#aa0000"; 
//		if (event.getLevel().toString().equals("FATAL"))
//			levelColor = "#ff0000"; 
//		
//		logEntry = "<tr>";
//		logEntry += "<td style=\"width:12%;\" class=\"logfile\" align=\"center\">"+df.format(new Date(event.timeStamp))+"</td>";
//		//logEntry += "<td class=\"logfile\" valign=\"top\">"+event.getThreadName()+"</td>";
//		logEntry += "<td style=\"width:4%;\" class=\"logfile\" align=\"center\"><span style=\"color:"+levelColor+"\">"+event.getLevel()+"</span></td>";
//		logEntry += "<td style=\"width:28%;\" class=\"logfile\" valign=\"top\"><div style=\"width:100%;overflow:hidden;\">"+event.getLoggerName()+"</div></td>";
//		logEntry += "<td style=\"width:56%;\" class=\"logfile\" valign=\"top\"><div style=\"width:100%;overflow:hidden;\">"+event.getMessage()+"</div></td>";
//		logEntry += "</tr>";
//
//		return logEntry;
//	}
	
}

